login_link = "//a[text()='Log In']"
login_email = "//input[@placeholder='Email Address']"
login_password = "//input[@placeholder='Password']"
login_button = "//button[text()='Log in']"
loading_banner = "//div[contains(@class,'modal-dialog')]//span[text()='Loading']"
ad_banner_close = "//div[contains(@class,'modal-dialog')]/parent::div//a[@class='modal-close']"
investment_container = "//article"
investor_name = "//h3"
investor_location = "//h3/following-sibling::div[1]"
total_investments = "//h3/following-sibling::div//span/parent::div[contains(normalize-space(),'investment')]"
total_exits = "//h3/following-sibling::div//span/parent::div[contains(normalize-space(),'exits')]"
emails = "//h3/following-sibling::div//span/parent::div[contains(normalize-space(),'Email')]"
total_ratings = "//div[contains(@class,'average-rating')][1]"
fundraiser_experience = "//label[text()='Fundraising experience']/parent::div//span[contains(@class,'rating')]"
post_funding_experience = "//label[text()='Post-funding experience']/parent::div//span[contains(@class,'rating')]"
questions = "//label[contains(@class,'question')]"
current_question = "//div[contains(@class,'modal-dialog')]//label[contains(@class,'question')]"
next_question = "//span[text()='NEXT QUESTION']"
load_reviews_button = "//span[text()='Load more reviews']/parent::button"
close_button = "//a[@class='modal-close']"
answers = "//div[contains(@class,'overflow')]//div[contains(@class,'answer')]//p"
answer_container = "//div[contains(@class,'overflow')]"